version: "3"
services:
  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "habrpguser"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
